### ISSUE TITLE
Receiving bellow error during execution (small domain)

### ISSUE THREAD

**Issue by mediapirate** [CyberArkLabs/ACLight#2]
â€œ\\â€ : The module 'â€œ' could not be loaded. For more information, run 'Import-Module â€œ'.
At C:\Users\jxc11\Downloads\ACLight-master\ACLight-master\ACLight.ps1:250 char:57
+         $NameArray = $_.UpdatedIdentityReference -Split(â€œ\\â€)
+                                                         ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (â€œ\\â€:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by MuadDib1969** [comment]
I received the same error as above. It did produce output though (all entities with extra permissions) but strangely said i didn't have any privileged accounts.

**Comment by Hechtov** [comment]
Hi @MuadDib1969 , @mediapirate - thanks for noticing me on this error.
It was because of weird conversion bugs of utf-8/unicode.
For example: the symbol " converted to â€œ.
I corrected those errors.
Please try to run the scan again and update me. Thanks.

**Comment by mediapirate** [comment]
Thanks, no logger getting this error.
