### ISSUE TITLE
Error message during "Accounts Analysis"

### ISSUE THREAD

**Issue by mediapirate** [CyberArkLabs/ACLight#3]
Get-NetGroupMember : Unable to find Group
At C:\Users\jxc11\Downloads\ACLight-master\ACLight-master\ACLight.ps1:635 char:54
+ ... Recursive = Get-NetGroupMember -domain $Domain -Recurse -UseMatchingR ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-NetGroupMember

**Comment by Hechtov** [comment]
Get-NetGroupMember is a known function from PowerView project.
I don't know why you have encountered this error.. to help I need more details.
What was the group name? Did you tried to run the scan on different domains? Does it happen only on one of your domain? It might be misconfiguration of the tested domain or something
