### ISSUE TITLE
Get-NetGroupMember : Unable to find Group

### ISSUE THREAD

**Issue by Khalidios** [CyberArkLabs/ACLight#4]
I received the below error 
Get-NetGroupMember : Unable to find Group
At D:\Downloads\ACLight-master\ACLight.ps1:635 char:54
+ ... Recursive = Get-NetGroupMember -domain $Domain -Recurse -UseMatchingR ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-NetGroupMember

**Comment by Hechtov** [comment]
Hi, it's should be ok and still continue the scan and provide results.
After the above query it has another group membership query function of 
$GroupMembersRecursive = Get-NetGroupMember -domain $Domain -GroupName $domainEntityName

**Comment by Khalidios** [comment]
I can see the bat file already close 
and i can see this file only (XYZ.COM- Full Output.csv)

**Comment by Hechtov** [comment]
Get-NetGroupMember is a known function from PowerView project:
[](https://github.com/PowerShellMafia/PowerSploit/tree/master/Recon)
I don't know why you have encountered this error.. to help I need more details.
What was the group name? Did you tried to run the scan on different domains? Does it happen only on one of your domain? It might be misconfiguration of the tested domain or something
Last thing to make sure, are you using the last updated version (15 days ago) of ACLight?
