### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by kushal-17** [CyberArkLabs/ACLight#6]
Sir can you please share technet c2 server script for research purposes please,if it's possible.

**Comment by Hechtov** [comment]
Hi @kushal-17 , what do you mean by "technet c2 server script"?
How is this script related to this ACLight scan?

**Comment by kushal-17** [comment]
Sorry sir it's been the way to contact. I m trying to contact cyberark for
technet c2.
Here the reference for you sir, what I mean to say is:-
https://www.cyberark.com/threat-research-blog/implementing-malware-command-control-using-major-cdns-high-traffic-domains/

Sir if it's possible to share or any help is provided by you is
appreciated. Please let me know if it's possible. And sorry mentioned above
it's been way to contact but not related to ACLight.

**Comment by Hechtov** [comment]
Hi @kushal-17
The post that you have mentioned was written by Shay Nahari, you can try contact him through his Twitter account @Red_Sec_Shay.
Please don't open unrelated issues again.
