### ISSUE TITLE
search filter is invalid message

### ISSUE THREAD

**Issue by waydaws** [CyberArkLabs/ACLight#7]
I had this warning message:
Scanning ACLs - Layer 4
WARNING: An error occurred while enumerating through a collection: The (&(name=*)(distinguishedname=*)(|(objectSid=S-1-5-21-915214332-934432599-2099212325-31100)(objectSid=S-1-5-21-915214332-93443259
9-2099212325-31990)(objectSid=))) search filter is invalid.

There were no previous layer warnings or errors.

**Comment by Hechtov** [comment]
Hi @waydaws 
It looks like a specific warning on that user's SID you got. It might be that in the Layer 4 scan, in one of the user's DACL entries, this SID was written but the user behinds that SID was removed so it's unavailable. I think it's not a problem in the filter but with the SID.
Did this warning come out and stopped the scan? or did the scan continue and you got the results afterwards?

**Comment by Hechtov** [comment]
It passed 5 years, with no response, this issue is a specific issue for a non valid search for a user with the problematic SID.
I didn't hear on other similar problems, so I'm closing the issue.
If anyone see this problem again, please let us know.
Thanks.
